mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_id: "0"

# –ù–∞—Å—Ç—Ä–æ–π–∫–∏ –¥–ª—è –ø–æ–∏—Å–∫–∞ –º–æ–¥–µ–ª–µ–π
model:
  run_name: "second_model_experiment"
  artifacts_path: "models"
  vectorizer: "tfidfvectoraizer.pkl"
  bayes: "naive_bayes.pkl"
  encoder: "labelencoder.pkl"

# –ù–∞—Å—Ç—Ä–æ–π–∫–∏ –¥–ª—è –ø–æ–∏—Å–∫–∞ —Ñ—É–Ω–∫—Ü–∏–∏ –ø—Ä–µ–ø—Ä–æ—Ü–µ—Å—Å–∏–Ω–≥–∞
preprocess:
  run_name: "Second dataset"
  artifact_path: "functions/clean_text_only.pkl"  # ‚Üê –∏—Å–ø—Ä–∞–≤–ª–µ–Ω–æ –Ω–∞ –ø—Ä–∞–≤–∏–ª—å–Ω–æ–µ –∏–º—è

# –¢–µ–∫—Å—Ç –¥–ª—è —Ç–µ—Å—Ç–∏—Ä–æ–≤–∞–Ω–∏—è
test_text: "–ú–µ–Ω—è –Ω–µ –ø—Ä–∏–≤–ª–µ–∫–ª–æ —Ç–∞–∫–æ–µ —Å–æ—á–µ—Ç–∞–Ω–∏–µ üò≠"