mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_id: "0"

model:
  run_name: "transformers_experiment_3"
  artifacts_path: "model"
  tokenizer_path: "tokenizer" 

tokenizer:
  max_length: 512
  padding: true
  truncation: true
  return_tensors: "pt"

test_text: "Можно было сделать чипсы и повкуснее"