mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_id: "0"

data:
  source_run: "First dataset"
  dataset_file: "first_experiment_dataset.csv"
  dataset_path: "datasets"

tokenizer:
  num_words: 2000
  oov_token: "<OOV>"
  filters: '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'
  lower: true
  split: " "
  char_level: false


training:
  test_size: 0.2
  val_size: 0.5 
  random_state: 42
  batch_size: 16
  epochs: 20

model:
  version: "1.0.0"
  embedding_dim: 128
  lstm_units: 64
  dropout_rate: 0.5
  dense_units: 10
  artifacts:
    model: "LSTM_ver_1.keras"
    tokenizer: "tokenizer.pkl"
    encoder: "encoder.pkl"