mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_id: "0"

# Конфигурация данных
data:
  source_run: "Second dataset"
  dataset_file: "second_experiment_dataset.csv"
  dataset_path: "datasets"

# Конфигурация токенизатора
tokenizer:
  num_words: 2000
  oov_token: null  # ← исправлено на null
  filters: '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'
  lower: true
  split: " "
  char_level: false
  analyzer: null  # ← добавляем analyzer

# Конфигурация обучения
training:
  test_size: 0.2
  val_size: 0.5
  random_state: 42
  batch_size: 16
  epochs: 40
  max_sequence_length: 100  # ← добавляем фиксированную длину

# Конфигурация модели CNN
model:
  version: "2.0.0"
  embedding_dim: 64
  conv_filters: 32
  conv_kernel_size: 3
  conv_activation: "relu"
  dropout_rate_1: 0.5
  dropout_rate_2: 0.2
  dense_units_1: 16
  dense_units_2: 10
  dense_activation_1: "relu"
  dense_activation_2: "softmax"
  artifacts:
    model: "CNN_ver_2.keras"  # ← меняем имя на CNN
    tokenizer: "tokenizer.pkl"
    encoder: "encoder.pkl"