defaults:
  - base

preprocess:
  method: "clean_only"
  
  clean_only:
    lowercase: true
    replace_emoji: true
    remove_punctuation: true
    remove_special_chars: true
    collapse_spaces: true
  
  output:
    dataset_csv: "Second_version.csv"
    preprocess_pickle: "preprocess_text_second.pkl"

mlflow:
  dataset_version: "2.0.0"
  experiment_name: "dataset_preprocessing"