model:
  model_name: "sberbank-ai/ruBert-base"
  version: "1.0.0"

tokenizer:
  max_length: 512
  padding: "max_length"
  truncation: true

data:
  dataset_path: "datasets"             # <-- папка
  dataset_file: "third_experiment_dataset.csv"   # <-- файл
  text_column: "text"
  label_column: "category"
  source_run: "Third dataset"          # <-- если у тебя датасет загружен внутри этого run

training:
  output_dir: "models_transformer/"
  num_train_epochs: 20
  learning_rate: 2e-5
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  weight_decay: 0.05
  logging_steps: 50
  save_total_limit: 2
  max_grad_norm: 1.0
  early_stopping_patience: 3
  test_size: 0.2
  val_size: 0.5
  random_state: 42
  metric_for_best_model: "f1-score"
  load_best_model_at_end: true

mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "Third dataset"     # <-- имя эксперимента
  run_name: "transformers_experiment_3"
  dataset_version: "3.0.0"

model:
  artifacts:
    model_dir: "artifacts/model"
    tokenizer_dir: "artifacts/tokenizer"
