model:
  name: "sberbank-ai/ruBert-base"
  version: "1.0.0"
  max_length: 512
  dropout:
    hidden: 0.1
    attention: 0.1
    classifier: 0.1

tokenizer:
  max_length: 512
  padding: "max_length"
  truncation: true

data:
  dataset_path: "datasets"
  dataset_file: "third_experiment_dataset.csv"
  text_column: "span"  # ← ИЗМЕНИЛ с "text" на "span" (как у тебя в датасете)
  label_column: "label" # ← ИЗМЕНИЛ с "category" на "label" (как у тебя в датасете)
  source_run: "Third dataset"
  train_size: 0.8
  val_size: 0.5
  random_state: 42

training:
  output_dir: "models_transformer/"
  num_train_epochs: 20
  learning_rate: 2e-5
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  weight_decay: 0.05
  logging_steps: 50
  save_total_limit: 2
  max_grad_norm: 1.0
  early_stopping_patience: 3
  metric_for_best_model: "f1-score"
  load_best_model_at_end: true

mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "0"  # ← ИЗМЕНИЛ на ID эксперимента "0" (как у тебя)
  run_name: "transformers_experiment_3"
  dataset_version: "3.0.0"

artifacts:
  model_dir: "artifacts/model"
  tokenizer_dir: "artifacts/tokenizer"